### ISSUE TITLE
在任務管理啟用任務後，更新task會出錯

### ISSUE THREAD

**Issue by jacky100888** [enilu/guns-lite#13]
發現是在UserIDAuditorConfig 中 :
HttpKit.getRequest().getHeader("Authorization");
quartz拿不到 request ，出nullpointexception
目前我的暫解是讓getCurrentAuditor 如果為空直接回傳 admin(id=1)
不知有沒有更好解決的方式!?

**Comment by enilu** [comment]
正常登陆后不会拿不到Authorization，除非你改了权限这款，允许任务管理这里不登陆可以操作？
能给出浮现步骤么
