### ISSUE TITLE
BASE64Encoder和BASE64Decoder 的引用问题

### ISSUE THREAD

**Issue by yangjrun** [enilu/guns-lite#17]
在使用java1.8以后的版本 会被移除掉。所以建议 使用
  <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>1.8</version>
  </dependency>
不知道 是否理解正确   如果有更好的解决方法可以私信我

**Comment by enilu** [comment]
可以用java8 新开始提供的java.util.Base64的Encoder和Decoder，这个性能比较好
