### ISSUE TITLE
文章题图可否设置宽高约束

### ISSUE THREAD

**Issue by 1783681442** [enilu/guns-lite#27]
个人觉得文章题图、配图或banner图片应该有宽高约束或自动裁剪功能，最起码应该有个可配置的地方，以方便用户上传

**Comment by enilu** [comment]
题图本身就是单独一个图片，上传的时候上传原始图片；至于要显示大小和位置位置，可以在显示的时候控制；
针对文章中的配图的大小和位置，编辑器tinymce本身就是支持的
